### ISSUE TITLE
Support for shadow endpoint

### ISSUE THREAD

**Issue by nelreina** [mankins/svelte-adapter-express#12]
Is there a way to use the endpoints created in sveltekit ? 

e.g.

routes
- todos.svelte
- todos.js

```javascript
// todos.js
export const GET = async () => {
  ...
}

```

adapter does not work with such construction. 

So I need to code the endpoint twice. Once for development and then create the route in express separately.

**Comment by mankins** [comment]
I'm not sure how much more life this adapter has in it, it was written for an era long ago... 

but I'd try exporting the routes like you have and then importing them in express. You'd have to manually setup the routes in express and there's likely an adapter layer with `req` and `res` you'd need to populate... I bet there's a better adapter that has this figured out, but I don't know of it.

**Comment by nelreina** [comment]
Yes I realize it , so the node-adapter can do what i want to do now too. So thanks for the adapter...
