### ISSUE TITLE
SSR error 1.0.0-next.154/155

### ISSUE THREAD

**Issue by autr** [mankins/svelte-adapter-express#3]
Hello, great to see this option as an adaptor!

I am getting this error though from within @sveltejs/kit/dist/ssr.js:

```
file:///Users/gilbert/Code/eze-app/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.154_svelte@3.42.1/node_modules/@sveltejs/kit/dist/ssr.js:1607
	if (incoming.path !== '/' && options.trailing_slash !== 'ignore') {
	                                     ^

TypeError: Cannot read property 'trailing_slash' of null
```

My svelte.config.js had been set to `ssr: false`, and I have also tried `ssr: true` - I'm taking a poke around the official adaptors but can't see anything obvious for this. Any help much appreciated!

**Comment by mankins** [comment]
Hmm, how are you calling the adapter?

**Comment by odama626** [comment]
This looks great, but I just got stuck at the same place after building and trying to run it

```
/build/chunks/app-e494f937.js:1211
  if (incoming.path !== "/" && options2.trailing_slash !== "ignore") {
                                        ^

TypeError: Cannot read properties of null (reading 'trailing_slash')
```

**Comment by odama626** [comment]
Ah, I figured it out, options is null because init hasn't been called, just got it working and going to submit a pr
